ARG ZYN_RUST_VERSION=1.91.0

FROM rust:$ZYN_RUST_VERSION-alpine as build

RUN apk add \
    build-base

RUN mkdir -p /project/src

# Create dummy main that allows compiling the project once,
# so that dependecies are installed
COPY zyn/Cargo.toml /project
RUN echo "fn main() {}" > /project/src/main.rs
RUN cd /project && cargo fetch

# Embedded websocket has a hardcoded limit of 16 headers by default. Recent udpate from Apple changed
# behavior in Ios in a way that is not enough anymore. Since embedded-websocket has changed it's
# interface drastically, it is easier to increase the limit by editing code... with sed
# It is licensed as MIT
RUN sed -i 's/EMPTY_HEADER; 16/EMPTY_HEADER; 20/g' /usr/local/cargo/registry/src/*/embedded-websocket-0.3.2/src/http.rs

# Compile dependencies
RUN cargo install --path /project

COPY zyn/ /project
RUN cargo build -r --manifest-path /project/Cargo.toml --target-dir /zyn-build-artifacts

from rust:$ZYN_RUST_VERSION-alpine

RUN apk add \
    bash \
    gpg \
    gpg-agent \
    expect

RUN mkdir /opt/zyn
COPY --from=build /zyn-build-artifacts/release/zyn /opt/zyn
COPY docker/entrypoint.sh /entrypoint.sh
RUN mkdir /data
ENTRYPOINT ["/entrypoint.sh"]
EXPOSE 80
VOLUME ["/data"]