#!/usr/bin/env python

import argparse
import os.path
import sys
import subprocess

import zyn_docker


PATH_DIR = os.path.dirname(os.path.abspath(__file__))
PATH_IMAGE = PATH_DIR + '/web'
PATH_SCRIPT_TO_PACK_SRC = PATH_IMAGE + '/create-src-tar.sh'
IMAGE_TAG = 'zyn-web-client'


def _main():
    parser = argparse.ArgumentParser(
        formatter_class=argparse.RawDescriptionHelpFormatter,
        description='Tools to run Zyn server in Docker container',
        epilog='''
Example:
run-zyn-in-docker $PWD/private.key 1234 $PWD/fullchain.pem $PWD/privkey.pem --init --bind-to "localhost:8080" --  --memory 2g --detach --rm
'''
    )

    parser.add_argument('web-server-port')
    parser.add_argument('zyn-server-ip')
    parser.add_argument('zyn-server-port')
    parser.add_argument('--ssl-path-to-cert')
    parser.add_argument('--ssl-path-to-key')
    parser.add_argument('--zyn-server-path-to-cert')
    parser.add_argument('--image-tag', default=IMAGE_TAG)
    parser.add_argument('--skip-pack-src', action='store_true')

    system_args = sys.argv[1:]
    docker_args = []
    if '--' in system_args:
        docker_args = system_args[system_args.index('--') + 1:]
        system_args = system_args[:system_args.index('--')]

    args = vars(parser.parse_args(system_args))

    print (args)

    tag = args['image_tag']
    port = args['web-server-port']
    server_ip = args['zyn-server-ip']
    server_port = args['zyn-server-port']

    path_zyn_server_cert = args['zyn_server_path_to_cert']
    path_image_server_cert = '/workdir/server-cert.pem'

    path_ssl_cert = args['ssl_path_to_cert']
    path_ssl_key = args['ssl_path_to_key']
    path_image_web_cert = '/workdir/web-cert.pem'
    path_image_web_key = '/workdir/web-key.pem'

    if not args['skip_pack_src']:
        zyn_docker.execute_script(PATH_SCRIPT_TO_PACK_SRC, PATH_DIR)

    zyn_docker.build_image(tag, PATH_IMAGE, PATH_DIR)

    run_cmd = [
        'docker',
        'run',
        '-p', '{}:8080/tcp'.format(port),
    ]

    if path_zyn_server_cert is not None:
        run_cmd += ['-v', '{}:{}'.format(path_zyn_server_cert, path_image_server_cert)]

    if path_ssl_cert is not None:
        run_cmd += ['-v', '{}:{}'.format(path_ssl_cert, path_image_web_cert)]
        run_cmd += ['-v', '{}:{}'.format(path_ssl_key, path_image_web_key)]

    run_cmd += docker_args

    run_cmd += [
        '{}:latest'.format(tag),
        '8080',
        server_ip,
        server_port,
    ]

    if path_zyn_server_cert:
        run_cmd += ['--zyn-server-path-to-cert', path_image_server_cert]

    if path_ssl_cert is not None:
        run_cmd += ['--ssl-path-to-cert', path_image_web_cert]
        run_cmd += ['--ssl-path-to-key', path_image_web_key]

    process = subprocess.Popen(
        run_cmd,
        cwd=PATH_DIR,
    )

if __name__ == '__main__':
    _main()
