Vagrant.configure("2") do |config|

  # username = "developer"
  # user_id = 1234
  # user_group_id = 1234

  config.vm.box = "debian/contrib-buster64"

  config.vm.network "forwarded_port", guest: 8080, host: 8080

  # Share project with VM
  config.vm.synced_folder "../../", "/zyn"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:

  config.vm.provider "virtualbox" do |vb|
    #   # Display the VirtualBox GUI when booting the machine
    #   vb.gui = true
    #
    # Customize the amount of memory on the VM:
    vb.memory = "4096"
    vb.cpus = 2

    # Set the name of the VM to include path to Vagrant file so that it is possible to
    # have multiple machinies running from diferent repos
    vb.name = "dev-zyn-" + File.dirname(__FILE__).gsub(":", "").gsub("/", "-").downcase
  end

  # Install puppet on VM
  config.vm.provision "shell", inline: <<-SHELL
     apt-get update
     apt-get install -y ansible
     whoami
     groups
     sudo -u vagrant ansible-playbook -vv /zyn/vm/development/vm.yml
  SHELL

end
