Vagrant.configure("2") do |config|

  config.vm.box = "debian/bookworm64"

  config.vm.network "forwarded_port", guest: 8080, host: 8080
  config.vm.network "forwarded_port", guest: 8081, host: 8081
  config.vm.network "forwarded_port", guest: 8082, host: 8082
  config.vm.network "forwarded_port", guest: 8083, host: 8083
  config.vm.network "forwarded_port", guest: 8084, host: 8084
  config.vm.network "forwarded_port", guest: 8085, host: 8085
  config.vm.network "forwarded_port", guest: 4433, host: 4433

  # Share project with VM
  config.vm.synced_folder "../../", "/zyn"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:

  config.vm.provider "virtualbox" do |vb|
    #   # Display the VirtualBox GUI when booting the machine
    #   vb.gui = true
    #
    # Customize the amount of memory on the VM:
    vb.memory = "4096"
    vb.cpus = 2

    # Set the name of the VM to include path to Vagrant file so that it is possible to
    # have multiple machinies running from diferent repos
    vb.name = "dev-zyn-" + File.dirname(__FILE__).gsub(":", "").gsub("/", "-").downcase
  end

  # Install puppet on VM
  config.vm.provision "shell", inline: <<-SHELL
     ansible_installed=1
     command -v ansible || ansible_installed=0
     if [ $ansible_installed -eq 0 ]; then
         apt update
         apt install -y gnupg
         echo "deb http://ppa.launchpad.net/ansible/ansible/ubuntu focal main" > /etc/apt/sources.list.d/ubuntu-ansible.list
         sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 93C4A3FD7BB9C367
         apt update
         apt install -y ansible
     else
         echo "Ansible already installed"
     fi
     sudo -u vagrant ansible-playbook -vv /zyn/vm/development/vm.yml
  SHELL

end
